declare module '@editorjs/embed'
declare module '@editorjs/list'
declare module '@editorjs/link'
declare module '@editorjs/table'
declare module '@editorjs/nested-list'
declare module '@editorjs/raw'
