import { buttonVariants } from '@/app/components/ui/Button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/app/components/ui/Card'
import { H1 } from '@/app/components/ui/Typography'
import { getAuthSession } from '@/lib/auth/auth'
import Link from 'next/link'
import { redirect } from 'next/navigation'
import LoginForm from './components/LoginForm'

export const metadata = {
	title: 'Login',
	description: 'Generated by create next app'
}

const LoginPage = async () => {
	const session = await getAuthSession()

	if (session) {
		if (session.user.role === 'ADMIN') return redirect('/admin')
		if (session.user.role === 'USER') return redirect('/manage')
	}

	return (
		<main className='wrapper flex flex-col items-center'>
			<H1 className='mb-4 mt-8'>Admin Only</H1>
			<Link href={'/'} className={buttonVariants({})}>
				Go back home
			</Link>

			<div className='mt-24 w-96 max-w-full'>
				<Card>
					<CardHeader>
						<CardTitle>Welcome back</CardTitle>
						<CardDescription>Log-in with provided credentials</CardDescription>
					</CardHeader>
					<CardContent>
						<LoginForm />
					</CardContent>
				</Card>
			</div>
		</main>
	)
}

export default LoginPage
