import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/app/components/ui/Card'
import LoginForm from './components/LoginForm'

export const metadata = {
	title: 'SdN | Login',
	description: 'Generated by create next app'
}

const LoginPage = () => {
	return (
		<main className='wrapper flex flex-col items-center'>
			<div className='mt-24 w-96 max-w-full'>
				<Card>
					<CardHeader>
						<CardTitle>Welcome back</CardTitle>
						<CardDescription>Log-in with provided credentials</CardDescription>
					</CardHeader>
					<CardContent>
						<LoginForm />
					</CardContent>
				</Card>
			</div>
		</main>
	)
}

export default LoginPage
