import { Toaster } from 'react-hot-toast'
import '../styles/globals.css'
import { Inter } from 'next/font/google'
import Providers from '@/app/components/Providers'
import Navbar from './components/modules/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'SdN',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en' className='dark' style={{ colorScheme: 'dark' }}>
			<body className={inter.className}>
				<Providers>
					<Navbar />
					{children}
					<Toaster />
				</Providers>
			</body>
		</html>
	)
}
