import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/app/components/ui/Card'
import RegisterForm from './components/RegisterForm'

export const metadata = {
	title: 'SdN | Register',
	description: 'Generated by create next app'
}

const RegisterPage = () => {
	return (
		<main className='wrapper flex flex-col items-center'>
			<div className='mt-24 w-96 max-w-full'>
				<Card>
					<CardHeader>
						<CardTitle>Register</CardTitle>
					</CardHeader>
					<CardContent>
						<RegisterForm />
					</CardContent>
				</Card>
			</div>
		</main>
	)
}

export default RegisterPage
